### ISSUE TITLE
Each request returns ERR_1010_002

### ISSUE THREAD

**Issue by e-defix** [jarnovanleeuwen/php-tikkie#4]
Each request which I send to the Tikki Api returns the error:

_[ERR_1010_002] The algorithm of the JWT is invalid_

I use the default algoritm: RS256

Is this a bug in the package or is this something else?

**Comment by jarnovanleeuwen** [comment]
The package has not recently changed and is heavily used by my own production environment without problems. Therefore, I think that the bug is on your side. Did you create your public and private key pair properly (2048 bits RSA), using the commands below? 

```bash
openssl genrsa -out private_rsa.pem 2048
openssl rsa -in private_rsa.pem -outform PEM -pubout -out public_rsa.pem
```

Are you loading your **private** key in this library?

Otherwise, please contact the Tikkie for Business team.
